---
- name: Install and Start nginx
  hosts: all
  become: yes
  become_method: sudo


  tasks:
    - name: Install nginx
      # shell: apt install nginx # the same with module below
      apt:
        name: nginx
        state: present # present mean to install
    - name: Start nginx
      # shell: systemctl start nginx
      service:
        name: nginx
        state: started