---
# hehe: https://citizix.com/using-ansible-to-install-and-configure-redis-6-on-debian-11/
- name: Install and setup Redis 6 in Debian
  hosts: all
  become: yes
  become_method: sudo
  vars:
    # redis_password: j2GfJuLFR8
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Set up Redis 6 repo
      shell: | 
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5F4349D6BF53AA0C
        curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
      
    - name: Install redis
      apt:
        name: redis-server
        update_cache: yes
      notify:
        - Enable: Redis

    - name: Set redis server pid file
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "^pidfile"
        line: "pidfile /var/run/redis/redis-server.pid"
      notify:
        - Restart Redis

    # - name: Secure redis with a password
    #   lineinfile:
    #     dest: /etc/redis/redis.conf
    #     regexp: '^(# )?requirepass \w*$'
    #     line: 'requirepass {{ redis_password }}'
    #     state: present
    #   notify:
    #     - Restart: Redis

    - name: Bind redis to 0.0.0.0
      lineinfile:
        dest: /etc/redis/redis.conf
        regexp: '^bind \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b$'
        line: 'bind 0.0.0.0'
        state: present
      notify:
        - Restart Redis

  handlers:
    - name: Restart Redis
      systemd:
        name: redis-server
        state: restarted

    - name: Start Redis
      systemd:
        name: redis-server
        state: started

    - name: Stop Redis
      systemd:
        name: redis-server
        state: stopped

    - name: Enable Redis
      systemd:
        name: redis-server
        enabled: yes